#!/bin/bash

mkdir /home/osboxes/desktop
mkdir /home/osboxes/downloads
mkdir /home/osboxes/pictures
mkdir /home/osboxes/videos
mkdir /home/osboxes/documents

for i in {i..5)
do 
mkdir folder$i
done

readarray -t a <users.txt

for i in "${a[@]}"
do
sudo adduser "$i"
sudo usermod -aG sudo "$i"
done


