#!/bin/bash

sudo mkdir desktop
sudo mkdir downloads
sudo mkdir pictures
sudo mkdir videos
sudo mkdir documents

for i in {i..5)
do 
mkdir folder$i
done

sudo adduser user1
sudo adduser user1 sudo
sudo adduser user2
sudo adduser user2 sudo 
sudo adduser user3
sudo adduser user3 sudo
sudo adduser user4
sudo adduser user4 sudo
sudo adduser user5
sudo adduser user5 sudo
